### ISSUE TITLE
Orbot/Tor support

### ISSUE THREAD

**Issue by ghost** [smarek/android-unbound-dns#19]
So is this possible? I'm using this with netguard instructions: https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ54

All it does is hangs the browser, no traffic is passed to orbot.

Any instructions to get the tcp traffic forwarded to tor? This issue may be related to  #18, I'm using that setup. However, I maybe understand that a setup using dnscrypt and tor may conflict. Is this correct?

I have some solutions I've yet to try out so I'd like an opinion or two about them, also some answers for the additional questions listed below, that is if anyone cares to answer.

the solutions: add tcp-upstream:yes and use 127.0.0.1@9050 as forward addr (the socks port) (does unbound even support socks? native or android?) or maybe try the tor dns port 5400 as forward addr, although it seems tor forwards port 53 via udp to the aformentioned port.

A bit of additional info- if you don't already need it- is tor uses the port 9040 to communicate via tcp. Does this port need to be taken into account as well as a redirector for example ports 80 and 443? Do I understand this info from tor documents correctly?

I hope I've been clear enough with all of this. Thanks for any help!

**Comment by licaon-kter** [comment]
You need to have both Orbot and Unbound with unchecked "apply rules".

**Comment by ghost** [comment]
No I've done that. Do you mean disregard the instruction set in the netguard faq?

**Comment by licaon-kter** [comment]
I'm not trying to contradict [my self](https://github.com/M66B/NetGuard/pull/490), why would you think I've done that?

So, are they both unchecked "apply rules" or what?

Else things will go in circles and not work: Orbot asks for the nodes IPs from Unbound which asks for a connection from Orbot which...

**Comment by ghost** [comment]
Again, ive already done that. Heres the spelled out version: yes, i have unchecked apply rules for both unbound and orbot.

It doesn't work.

What netguard version was tested as working with tor at the time you made that addition to the faq? Or I can do that math myself if youre going to say 'use the latest version'.

**Comment by licaon-kter** [comment]
So step by step:

* Using Unbound (without routing all through Tor) works ok, right?

* Using FAQ#54 (without routing port 53 through Unbound) works ok, right?

**Comment by ghost** [comment]
Excuse me, you can't answer a question with another question.

So again, what netguard version were you using when you wrote that faq?

Now, after you have answered me I will answer you.

**Comment by ghost** [comment]
So, back to helping myself to sort out an issue with this android mess.... great.

Truly, what are you guys here for? The laughs?

**Comment by licaon-kter** [comment]
So much entitlement... wow

**Comment by ghost** [comment]
The reason I ask what version of netguard was being used when tor was working with it is because (maybe providing a reason for asking that question may help you to answer it) the socks proxy inside netguard version 2.89 seems is broken, or, it doesn't work for me.

Everything works if I'm using the http proxy settings 127.0.0.1:8118.

So, i'll try to ask this question once more, and, for the record, this is the 3rd time I'm asking.

The question is: what's the version of netguard that has a working socks proxy?

**Comment by licaon-kter** [comment]
Yes, I guess it was written at 2.89.

Now, testing with 2.98 works fine here for me (port 9050, both apps unchecked "apply rules"): DNS resolving via a dnscrypt server and http exit through Tor.

I'll try later to test with the latest NetGuard version too, albeit I don't remember seeing the SOCKS part being modified in the mean tine (but he did touch the DNS section).

**Comment by smarek** [comment]
@itspull could you please provide your full used unbound.conf? Thank you

**Comment by ghost** [comment]
> could you please provide your full used unbound.conf? Thank you

@smarek ok, i'm about sure you two, including @licaon-kter, are either not using english as your first language, or, even better yet, are not proficient readers.

which, if the the latter is true, would explain alot.

@smarek if you check my op, i've clearly stated that i'm using the setup- and hence the conf- provided by the licaon guy, which is referenced in #18.

download that package and check the unbound.conf provided with it.

i have reservations about his package, as he won't open source it, despite being pressed about it.

and yet, that's what i'm using at the moment.

or, if you prefer, i can upload it.

**Comment by licaon-kter** [comment]
Easy on the insults, again, stop with the entitlement.
He does not need to read all this chatter, since you meddle in the settings you surely have it at hand.

Again, about the open source thing... I'll repeat, everything I did can be seen/used/whatever, it's in the package.

**unbound.conf.default**

```
server:
        verbosity: 1
        interface: 127.0.0.1
        # interface: ::1
        # interface: 0.0.0.0
        port: 5300
        do-daemonize: no
        # access-control: 0.0.0.0/0 refuse
        # access-control: 0.0.0.0/0 allow_snoop
        # access-control: ::0/0 refuse
        # access-control: ::0/0 allow_snoop
        # do-not-query-address: 127.0.0.1/8
        # do-not-query-address: ::1
        do-not-query-localhost: no
        # prefetch: yes
        # prefetch-key: yes
        directory: ""
        chroot: ""
        username: ""
        logfile: "mainlog"
        pidfile: "unbound.pid"
        auto-trust-anchor-file: "root.key"
        harden-dnssec-stripped: yes
        qname-minimisation: yes

forward-zone:
        name: "."
        forward-addr: 127.0.0.1@5301
        forward-addr: 127.0.0.1@5302

remote-control:
        control-enable: yes
        # control-interface: 0.0.0.0
        control-interface: 127.0.0.1
        # control-interface: ::1
        control-port: 8953
        server-key-file: "unbound_server.key"
        server-cert-file: "unbound_server.pem"
        control-key-file: "unbound_control.key"
        control-cert-file: "unbound_control.pem"
```
